import pandas as pd
df = pd.read_csv('exam_scores.csv')
print("Details of all students :\n")
print(df)
print("Destails of first 3 students: \n")
print(df[:3])
print("Names and scores of all students: \n")
print(df[['Name','Scores']])
print("Details of qualified students: \n")
print(df[df["Qualified"]=="yes"])
print("Details of students who made more than 1 attempts: ")
print(df[df["Attempts"]>1])
print("mean score of all students: \n")
print(round(df["Scores"].mean()),2)
print("Details of students in decreasing order according their scores: \n")
print(df.sort_values("Scores",ascending=False))